sudo: required
# services:
#   - docker
before_install:
  - sudo apt-get update && sudo apt-get install -y libxml2-utils make pcregrep
  - gem install commaparty:0.0.2 nokogiri:1.5.6
  # see https://github.com/travis-ci/travis-cookbooks/issues/964
  - rm -f /opt/jdk_switcher/jdk_switcher.sh
script:
  # skip webservice test for now because it uses pax-exam-container-forked which sometimes causes problems
  - make framework/webservice/.dependencies
  - touch framework/webservice/.last-tested
  # skip because it takes too much time to run all tests
  # - make check
  - make GTAR=/bin/tar dist-docker-image
  - cd assembly && make check-docker
after_failure:
 - cat maven.log
