sudo: required
# services:
#   - docker
before_install:
  - sudo apt-get update && sudo apt-get install -y libxml2-utils make pcregrep
  - gem install commaparty:0.0.2 nokogiri:1.5.6
  # see https://github.com/travis-ci/travis-cookbooks/issues/964
  - rm -f /opt/jdk_switcher/jdk_switcher.sh
script:
  - make RUBY=ruby dist-docker-image
  - make RUBY=ruby -C assembly check-docker
after_failure:
 - cat maven.log
