language: java
jdk: oraclejdk7
after_success:
- ./upload.sh
- ./publish-javadoc.sh
before_install:
- openssl aes-256-cbc -K $encrypted_395561562480_key -iv $encrypted_395561562480_iv
  -in secring.gpg.enc -out secring.gpg -d
