name: DAISY Pipeline 2
collections:
  wiki:
    output: true
    permalink: /wiki/:path/
defaults:
  - scope: {path: wiki/main}
    values: {layout: wiki-main}
  - scope: {path: wiki/gui}
    values: {layout: wiki-gui}
  - scope: {path: wiki/webui}
    values: {layout: wiki-webui}
markdown: kramdown
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false
    css: class
baseurl: "/pipeline"
site_base: "http://daisy.github.io"
meta_file: _meta.ttl
