name: DAISY Pipeline 2
collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  wiki_gui:
    output: true
    permalink: /wiki/gui/:path/
  wiki_webui:
    output: true
    permalink: /wiki/webui/:path/
defaults:
  - scope: {path: "", type: wiki}
    values: {layout: wiki}
  - scope: {path: "", type: wiki_gui}
    values: {layout: wiki-gui}
  - scope: {path: "", type: wiki_webui}
    values: {layout: wiki-webui}
markdown: kramdown
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false
    css: class
baseurl: "/pipeline"
site_base: "http://daisy.github.io"
meta_file: _meta.ttl
