name: DAISY Pipeline 2
markdown: kramdown
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false
    css: class
baseurl: "/pipeline"
site_base: "http://daisy.github.io"
meta_file: meta.ttl
exclude:
  - /meta.ttl